---
title: "BC COVID Tracker"
author: "Daniel J. McDonald"
date: "Last updated at `r format(Sys.time(), '%d %B, %Y - %H:%M',tz='America/Vancouver')`"
output: rmdformats::material
css: styles.css
---

```{r setup-data, warning = FALSE, message = FALSE, echo=FALSE}
library(CanCovidData)
library(magrittr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(scales)
library(plotly)
library(withr)
n_recent <- 90
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width = 8, fig.height = 4, echo = FALSE)
dat <- get_british_columbia_case_data() %>%
  rename(HA = `Health Authority`, Date = `Reported Date`,
         Age = `Age group`) %>%
  filter(Date >= ymd("2020-03-01"))
pop_bc <- 5147712
pop_ha <- readRDS("population_ha.RDS")
pop_age <- readRDS("population_age.RDS")

cases <- dat %>%
  count(Date, name = "Cases")
cases_ha <- dat %>% 
  filter(HA != "Out of Canada") %>%
  count(Date, HA, name = "Cases")
cases_ha <- cases_ha %>%
  tidyr::expand(Date, HA) %>%
  left_join(cases_ha) %>%
  mutate(Cases = coalesce(Cases, 0)) %>% 
  left_join(pop_ha) %>%
  group_by(HA) 

cases_age <- dat %>%
  count(Date, Age, name = "Cases")
cases_age <- cases_age %>%
  tidyr::expand(Date, Age) %>%
  left_join(cases_age) %>%
  mutate(Cases = coalesce(Cases, 0)) %>%
  left_join(pop_age) %>%
  group_by(Age)
theme_set(theme_bw(base_family = "Times", base_size = 16))
log10_breaks = c(0,2,5,10,25,50,100,250,500,1000,2500,5000)

```


```{r my-kernel-smoother}
my_ks <- function(x, y, band = 14, deg = 0L) {
  dmat <- as.matrix(dist(x))
  K <- dnorm(dmat, 0, sd = band * .39) # puts 20% outside band
  if (deg == 1L) { # local linear
    W <- K * dmat
    S1 <- colSums(W)
    S2 <- colSums(W * dmat)
    K <- K * (1 -  sweep(K, 2, S1/S2, "*"))
  } else {
    K <- sweep(K, 1, rowSums(K), '/')
  }
  fit <- K %*% y
  loocvs <- (y - fit)^2 / (1 - diag(K))^2
  loocv <- mean( (y - fit)^2 / (1 - diag(K))^2 )
  out <- list(
    fit = fit, 
    loocv = loocv, 
    cvse = sd(loocvs) / sqrt(length(y) - 1)
  )
  out
}


my_smooth <- function(x, y, 
                      minband = 7, deg = 1L, maxband = 21, nbands = 25,
                      best = c("bands.1se", "bands.min")) {
  best <- match.arg(best)
  bands <- seq(minband, maxband, length.out = nbands)
  l <- lapply(bands, function(b) my_ks(x, y, b, deg))
  cvm <- sapply(l, function(x) x$loocv)
  cvsd <- sapply(l, function(x) x$cvse)
  cvmin = min(cvm, na.rm = TRUE)
  idmin = cvm <= cvmin
  bands.min = max(bands[idmin], na.rm = TRUE)
  idmin = match(bands.min, bands)
  selected <- idmin
  semin = (cvm + cvsd)[idmin]
  id1se = cvm <= semin
  bands.1se = max(bands[id1se], na.rm = TRUE)
  id1se = match(bands.1se, bands)
  if (best == "bands.1se") selected <- id1se
  return(list(fit = l[[selected]]$fit, 
              loocv = cvm, 
              bands.min = bands.min,
              bands.1se = bands.1se))
}

daily <- function(x) decimal_date(x) * 365
```

```{r}
tooltip.maker <- function(time = c("recent", "all"), is.s = T, scale = c("raw", "log", "cap"), by = c("all", "ha", "age"), item = NULL) {
  if (by == "all") {
    if (time == "recent") data <- recent_cases
    if (time == "all") data <- all_cases
    if (is.s & scale == "raw") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$s,2)))
    if (is.s & scale == "log") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$ls,2)))
    if (is.s & scale == "cap") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$ps,2)))
    if (!is.s & scale == "cap") return(paste("Date: ", data$Date, "<br>Cases per 100K: ", round(data$Cases / pop_bc * 1e5, 2)))
  }
  
  if (by == "ha") {
    if (time == "recent") data <- recent_ha[recent_ha$HA == item,]
    if (time == "all") data <- all_ha[all_ha$HA == item,]
    if (is.s & scale == "raw") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$s,2), "<br>HA: ", item))
    if (is.s & scale == "log") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$ls,2), "<br>HA: ", item))
    if (is.s & scale == "cap") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$ps,2), "<br>HA: ", item))
    if (!is.s & scale == "cap") return(paste("Date: ", data$Date, "<br>Cases per 100K: ", round(data$Cases / pop_ha$pop[pop_ha$HA == item] * 1e5, 2), "<br>HA: ", item))
  }
  
  if (by == "age") {
    if (time == "recent") data <- recent_age[recent_age$Age == item,]
    if (time == "all") data <- all_age[all_age$Age == item,]
    if (is.s & scale == "raw") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$s,2), "<br>Age: ", item))
    if (is.s & scale == "log") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$ls,2), "<br>Age: ", item))
    if (is.s & scale == "cap") return(paste("Date: ", data$Date, "<br>Smoother: ", round(data$ps,2), "<br>Age: ", item))
    if (!is.s & scale == "cap") return(paste("Date: ", data$Date, "<br>Cases per 100K: ", round(data$Cases / pop_age$pop[pop_age$Age == item] * 1e5, 2), "<br>Age: ", item))
  }
}
```



# Recent data (last `r n_recent` days) {.tabset}

```{r}
recent_cases <- cases %>% 
  filter(Date >= Sys.Date() - n_recent) %>%
  mutate(s = my_smooth(daily(Date), Cases, deg = 0L)$fit,
         ls = 10^(my_smooth(daily(Date), log10(Cases + 1), deg = 0L)$fit) - 1,
         ps = my_smooth(daily(Date), Cases / pop_bc * 1e5, deg = 0L)$fit)

recent_ha <- cases_ha %>% 
  filter(Date >= Sys.Date() - n_recent) %>%
  mutate(s = my_smooth(daily(Date), Cases, deg = 0L)$fit,
         ls = 10^(my_smooth(daily(Date), log10(Cases + 1), deg = 0L)$fit)-1,
         ps = my_smooth(daily(Date), Cases / pop * 1e5, deg = 0L)$fit)

recent_age <- cases_age %>%
  filter(Age != "Unknown", Date >= Sys.Date() - n_recent) %>%
  mutate(s = my_smooth(daily(Date), Cases, deg = 0L)$fit,
         ls = 10^(my_smooth(daily(Date), log10(Cases + 1), deg = 0L)$fit) - 1,
         ps = my_smooth(daily(Date), Cases / pop * 1e5, deg = 0L)$fit)
```

## All BC {.tabset}

### Raw

```{r}
(ggplot(recent_cases, aes(Date, Cases)) +
  geom_point(aes(y=Cases),colour = "darkblue", shape = 16, alpha = .4) +
  geom_line(aes(y=s), size = 1.5, colour = "darkblue")) %>%
  ggplotly(tooltip = c("Date", "Cases")) %>%
  style(text = tooltip.maker("recent", T, "raw", "all"), traces=2)
```

### Log scale 

```{r}
(ggplot(recent_cases, aes(Date, Cases)) +
  geom_point(aes(y=Cases), colour = "darkblue", shape = 16, alpha = .4) +
  geom_line(aes(y=ls), size = 1.5, colour = "darkblue") +
  scale_y_continuous(trans = pseudo_log_trans(base = 10), 
                     breaks = log10_breaks) +
  ylab("Cases (log scale)")) %>%
  ggplotly(tooltip = c("Date", "Cases")) %>%
  style(text = tooltip.maker("recent", T, "log", "all"), traces = 2)

```



### Per capita

```{r}
(ggplot(recent_cases, aes(Date, Cases / pop_bc * 1e5)) +
  geom_point(colour = "darkblue", shape = 16, alpha = .4) +
  geom_line(aes(y=ps), size = 1.5, colour = "darkblue") +
  ylab("Cases per 100K population")) %>%
  ggplotly() %>%
  style(text = tooltip.maker("recent", F, "cap", "all"), traces=1) %>% 
  style(text = tooltip.maker("recent", T, "cap", "all"), traces=2)
```


## By Health Authority {.tabset}


### Raw

```{r}
s.tooltip.ha <- function(ha) paste("Date: ", recent_ha$Date[recent_ha$HA == ha], "<br>Smoother: ", round(recent_ha$s[recent_ha$HA == ha],2), "<br>HA: ", ha)

(ggplot(recent_ha, aes(Date, Cases, colour = HA)) +
  geom_point(aes(y = Cases), shape = 16, alpha = .4) +
  geom_line(aes(y = s), size = 1.5) +
  scale_colour_brewer(palette = "Set1") +
  theme(legend.title = element_blank(), legend.position = "bottom")) %>%
  ggplotly(tooltip = c("Date", "Cases", "HA")) %>%
  style(text = tooltip.maker("recent", T, "raw", "ha", "Fraser"), traces = 6) %>%
  style(text = tooltip.maker("recent", T, "raw", "ha", "Interior"), traces = 7) %>%
  style(text = tooltip.maker("recent", T, "raw", "ha", "Northern"), traces = 8) %>%
  style(text = tooltip.maker("recent", T, "raw", "ha", "Vancouver Coastal"), traces = 9) %>%
  style(text = tooltip.maker("recent", T, "raw", "ha", "Vancouver Island"), traces = 10)

```

### Log scale

```{r}
(ggplot(recent_ha, aes(Date, Cases, colour = HA)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ls), size = 1.5) +
  scale_colour_brewer(palette = "Set1") +
  scale_y_continuous(trans = pseudo_log_trans(base = 10), 
                     breaks = log10_breaks) +
  ylab("Cases (log scale)") +
  theme(legend.title = element_blank(), legend.position = "bottom")) %>%
  ggplotly(tooltip = c("Date", "Cases", "HA")) %>%
  style(text = tooltip.maker("recent", T, "log", "ha", "Fraser"), traces = 6) %>%
  style(text = tooltip.maker("recent", T, "log", "ha", "Interior"), traces = 7) %>%
  style(text = tooltip.maker("recent", T, "log", "ha", "Northern"), traces = 8) %>%
  style(text = tooltip.maker("recent", T, "log", "ha", "Vancouver Coastal"), traces = 9) %>%
  style(text = tooltip.maker("recent", T, "log", "ha", "Vancouver Island"), traces = 10)
```

### Per capita

```{r}
(ggplot(recent_ha, 
       aes(Date, Cases / pop * 1e5, colour = HA)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ps), size = 1.5) +
  scale_colour_brewer(palette = "Set1") +
  ylab("Cases per 100K population") +
  theme(legend.title = element_blank(), legend.position = "bottom")) %>%
  ggplotly(tooltip = c("Date", "Cases", "HA")) %>%
  style(text = tooltip.maker("recent", F, "cap", "ha", "Fraser"), traces = 1) %>%
  style(text = tooltip.maker("recent", F, "cap", "ha", "Interior"), traces = 2) %>%
  style(text = tooltip.maker("recent", F, "cap", "ha", "Northern"), traces = 3) %>%
  style(text = tooltip.maker("recent", F, "cap", "ha", "Vancouver Coastal"), traces = 4) %>%
  style(text = tooltip.maker("recent", F, "cap", "ha", "Vancouver Island"), traces = 5) %>%
  style(text = tooltip.maker("recent", T, "cap", "ha", "Fraser"), traces = 6) %>%
  style(text = tooltip.maker("recent", T, "cap", "ha", "Interior"), traces = 7) %>%
  style(text = tooltip.maker("recent", T, "cap", "ha", "Northern"), traces = 8) %>%
  style(text = tooltip.maker("recent", T, "cap", "ha", "Vancouver Coastal"), traces = 9) %>%
  style(text = tooltip.maker("recent", T, "cap", "ha", "Vancouver Island"), traces = 10)
```



## By Age Group {.tabset}

### Raw 

```{r}
(ggplot(recent_age, aes(Date, Cases, colour = Age)) +
  geom_point(aes(y = Cases), shape = 16, alpha = .4) +
  geom_line(aes(y = s), size = 1.5) +
  scale_colour_viridis_d() +
  theme(legend.title = element_blank(),
        legend.position = "bottom")) %>%
  ggplotly() %>%
  style(text = tooltip.maker("recent", T, "raw", "age", "<10"), traces = 11)
```

### Log scale

```{r}
ggplot(recent_age, aes(Date, Cases, colour = Age)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ls), size = 1.5) +
  scale_colour_viridis_d() + 
  scale_y_continuous(trans = pseudo_log_trans(base = 10), 
                     breaks = log10_breaks) +
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  ylab("Cases (log scale)")
```

### Per capita

```{r}
ggplot(recent_age, aes(Date, Cases / pop * 1e5, colour = Age)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ps), size = 1.5) +
  scale_colour_viridis_d() +
  ylab("Cases per 100K population") +
  theme(legend.title = element_blank(), legend.position = "bottom")
```

# Since March 2020 {.tabset}

```{r}
all_cases <- cases %>% 
  mutate(
    s = my_smooth(daily(Date), Cases, deg = 0L, 
                  minband = 14, maxband = 35)$fit,
    ls = 10^(my_smooth(daily(Date), log10(Cases + 1), deg = 0L,
                       minband = 14, maxband = 35)$fit) - 1,
    ps = my_smooth(daily(Date), Cases / pop_bc * 1e5, deg = 0L,
                   minband = 14, maxband = 35)$fit)
all_ha <- cases_ha %>% 
  mutate(
    s = my_smooth(daily(Date), Cases, deg = 0L, 
                  minband = 14, maxband = 35)$fit,
    ls = 10^(my_smooth(daily(Date), log10(Cases + 1), deg = 0L,
                       minband = 14, maxband = 35)$fit) - 1,
    ps = my_smooth(daily(Date), Cases / pop * 1e5, deg = 0L,
                   minband = 14, maxband = 35)$fit)
all_age <- cases_age %>%
  filter(Age != "Unknown") %>%
  mutate(
    s = my_smooth(daily(Date), Cases, deg = 0L, 
                  minband = 14, maxband = 35)$fit,
    ls = 10^(my_smooth(daily(Date), log10(Cases + 1), deg = 0L,
                       minband = 14, maxband = 35)$fit) - 1,
    ps = my_smooth(daily(Date), Cases / pop * 1e5, deg = 0L,
                   minband = 14, maxband = 35)$fit)
```


## All BC {.tabset}

### Raw scale

```{r}
ggplot(all_cases, aes(Date, Cases)) +
  geom_point(colour = "darkblue", shape = 16, alpha = .4) +
  geom_line(aes(y=s), size = 1.5, colour = "darkblue") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```

### Log scale

```{r}
ggplot(all_cases, aes(Date, Cases)) +
  geom_point(colour = "darkblue", shape = 16, alpha = .4) +
  geom_line(aes(y=s), size = 1.5, colour = "darkblue") +
  scale_y_continuous(trans = pseudo_log_trans(base = 10), 
                     breaks = log10_breaks) +
  ylab("Cases (log scale)") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```

### Per capita

```{r}
ggplot(all_cases, aes(Date, Cases / pop_bc * 1e5)) +
  geom_point(colour = "darkblue", shape = 16, alpha = .4) +
  geom_line(aes(y=ps), size = 1.5, colour = "darkblue") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") +
  ylab("Cases per 100K population")
```


## By Health Authority {.tabset}

### Raw

```{r}
ggplot(all_ha, aes(Date, Cases, colour = HA)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = s), size = 1.5) +
  scale_colour_brewer(palette = "Set1") +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```

### Log scale

```{r}
ggplot(all_ha, aes(Date, Cases, colour = HA)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ls), size = 1.5) +
  scale_colour_brewer(palette = "Set1") +
  scale_y_continuous(trans = pseudo_log_trans(base = 10), 
                     breaks = log10_breaks) +
  ylab("Cases (log scale)") +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```

### Per capita

```{r}
ggplot(all_ha, aes(Date, Cases / pop * 1e5, colour = HA)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ps), size = 1.5) +
  scale_colour_brewer(palette = "Set1") +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") +
  ylab("Cases per 100K population")
```


## By Age Group {.tabset}

### Raw

```{r}

ggplot(all_age, aes(Date, Cases, colour = Age)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = s), size = 1.5) +
  scale_colour_viridis_d() +
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```

### Log scale

```{r}
ggplot(all_age, aes(Date, Cases, colour = Age)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ls), size = 1.5) +
  scale_colour_viridis_d() + 
  scale_y_continuous(trans = pseudo_log_trans(base = 10), 
                     breaks = log10_breaks) +
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  ylab("Cases (log scale)") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```

### Per capita

```{r}
ggplot(all_age, aes(Date, Cases / pop * 1e5, colour = Age)) +
  geom_point(shape = 16, alpha = .4) +
  geom_line(aes(y = ps), size = 1.5) +
  scale_colour_viridis_d() + 
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  ylab("Cases per 100K population") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")
```
